///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestCIProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestCIProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("feec8763-4a4c-40f7-a7c0-c0c7d0c1fc7b")]
    public partial class TestCIProjectRepository : RepoGenBaseFolder
    {
        static TestCIProjectRepository instance = new TestCIProjectRepository();
        TestCIProjectRepositoryFolders.MainWindowAppFolder _mainwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TestCIProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("feec8763-4a4c-40f7-a7c0-c0c7d0c1fc7b")]
        public static TestCIProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestCIProjectRepository() 
            : base("TestCIProjectRepository", "/", null, 0, false, "feec8763-4a4c-40f7-a7c0-c0c7d0c1fc7b", ".\\RepositoryImages\\TestCIProjectRepositoryfeec8763.rximgres")
        {
            _mainwindow = new TestCIProjectRepositoryFolders.MainWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("feec8763-4a4c-40f7-a7c0-c0c7d0c1fc7b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainWindow folder.
        /// </summary>
        [RepositoryFolder("737c188a-5869-480f-b2b5-d29e86f914a8")]
        public virtual TestCIProjectRepositoryFolders.MainWindowAppFolder MainWindow
        {
            get { return _mainwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class TestCIProjectRepositoryFolders
    {
        /// <summary>
        /// The MainWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("737c188a-5869-480f-b2b5-d29e86f914a8")]
        public partial class MainWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _button2Info;

            /// <summary>
            /// Creates a new MainWindow  folder.
            /// </summary>
            public MainWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainWindow", "/form[@wpfnative='True' and @title='MainWindow' and @processname='MyCIProject']", parentFolder, 30000, null, true, "737c188a-5869-480f-b2b5-d29e86f914a8", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "?/?/button[@text='Button 1']", 30000, null, "769a9590-ee38-4709-9063-ddd17f8d0d38");
                _button2Info = new RepoItemInfo(this, "Button2", "?/?/button[@text='Button 2']", 30000, null, "dc12b0c1-56e8-41af-ac6d-aab518a9d94d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("737c188a-5869-480f-b2b5-d29e86f914a8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("737c188a-5869-480f-b2b5-d29e86f914a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("769a9590-ee38-4709-9063-ddd17f8d0d38")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("769a9590-ee38-4709-9063-ddd17f8d0d38")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("dc12b0c1-56e8-41af-ac6d-aab518a9d94d")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("dc12b0c1-56e8-41af-ac6d-aab518a9d94d")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }
        }

    }
#pragma warning restore 0436
}